name: Continuous Deployment
on: workflow_dispatch

jobs:
  database:
    name: Deploy database
    uses: hanatole/deployer/.github/workflows/cd.yml@main
    with:
      project_directory: "/srv/todo"
      traefik_rule: ""
      network_name: traefiknetwork
      service_name: todo-database
      service_port: 5432
      docker_image: "postgres:18.1-alpine3.23"
      tier: "database"
      project_name: "todo"
      volume_path: "/var/lib/postgresql/data"
      db_type: "postgresql"
    secrets: inherit

  deploy:
    name: Deploy backend
    uses: hanatole/deployer/.github/workflows/cd.yml@main
    with:
      project_directory: "/srv/todo"
      traefik_rule: "Host(`api.ah.imc.chillo.fr`)"
      network_name: traefiknetwork
      service_name: todo-backend
      service_port: 8000
      docker_image: "image"
      tier: "backend"
      add_labels: True
      project_name: "todo"
    secrets: inherit
