name: Continuous Deployment
on:
  workflow_run:
    workflows: [ "Continuous Integration" ]
    types: [ completed ]

jobs:
  package:
    name: Package and push archetype
    runs-on: ubuntu-24.04
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'

    outputs:
      tag: ${{ steps.meta.outputs.tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Login to docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ vars.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Compute image tag
        id: meta
        run: |
          SHA="${{ github.event.workflow_run.head_sha }}"
          test -n "$SHA"
          echo "tag=${{ vars.REGISTRY_USER }}/${{ vars.PROJECT }}:${SHA::7}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ vars.REGISTRY_USER }}/${{ vars.PROJECT }}:latest
            ${{ steps.meta.outputs.tag }}
  

  deploy-database:
    name: Deploy database
    needs: package
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'

    uses: hanatole/deployer/.github/workflows/cd.yml@main
    with:
      project_directory: "/srv/todo"
      traefik_rule: ""
      network_name: traefiknetwork
      service_name: todo-database
      service_port: 5432
      docker_image: "postgres:18.1-alpine3.23"
      tier: "database"
      volume_path: "/var/lib/postgresql/data"
      db_type: "postgresql"
    secrets: inherit

  deploy-backend:
    name: Deploy backend
    needs:
      - package
      - deploy-database
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'

    uses: hanatole/deployer/.github/workflows/cd.yml@main
    with:
      project_directory: "/srv/todo"
      traefik_rule: "Host(`api.ah.imc.chillo.fr`)"
      network_name: traefiknetwork
      service_name: todo-backend
      service_port: 8000
      docker_image: "${{needs.package.outputs.tag}}"
      tier: "backend"
    secrets: inherit