name: Continuous Deployment
on: workflow_dispatch

jobs:
  deploy:
    uses: hanatole/deployer/.github/workflows/cd.yml@main
    with:
      project_directory: "/srv/todo/backend"
      traefik_rule: "Host(`api.ah.imc.chillo.fr`)"
      network_name: traefiknetwork
      service_name: todo-backend
      service_port: 8000
      docker_image: "image"
      add_labels: "true"
    secrets: inherit
