name: Continuous Integration and Deployment
on:
  push:
  pull_request:
    branches:
      - main
env:
  image: "${{ vars.REGISTRY_USER }}/${{ vars.PROJECT }}"
jobs:
  check:
    name: Run linters and tests
    runs-on: ubuntu-24.04
    env:
      DB_USER: todo
      DB_NAME: todo
      DB_PASSWORD: todo
      DB_PORT: 5432
      DB_HOST: localhost
      SECRET_KEY: 0e5c4f6a22e45d48114af
      DEBUG: True
      ALLOWED_HOSTS: localhost
      DJANGO_SETTINGS_MODULE: conf.settings

    services:
      todo:
        image: postgres:18.1-alpine3.23
        env:
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
          POSTGRES_DB: ${{ env.DB_NAME }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Install dependencies
        uses: astral-sh/setup-uv@v7
        with:
          version: 0.9.22
          python-version: 3.12

      - name: Run linters
        run: uv run ruff check .

      - name: Run tests
        run: uv run pytest

  package:
    name: Package and deploy application
    runs-on: ubuntu-24.04
    needs: check
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Login to docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ vars.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: "${{env.image}},${{env.image}}:$(git rev-parse --short HEAD)"

  deploy-database:
    name: Deploy database
    needs: package
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    uses: hanatole/deployer/.github/workflows/cd.yml@main
    with:
      project_directory: "/srv/todo"
      traefik_rule: ""
      network_name: traefiknetwork
      service_name: todo-database
      service_port: 5432
      docker_image: "postgres:18.1-alpine3.23"
      tier: "database"
      volume_path: "/var/lib/postgresql/data"
      db_type: "postgresql"
    secrets: inherit

  deploy-backend:
    name: Deploy backend
    needs: deploy-database
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    uses: hanatole/deployer/.github/workflows/cd.yml@main
    with:
      project_directory: "/srv/todo"
      traefik_rule: "Host(`api.ah.imc.chillo.fr`)"
      network_name: traefiknetwork
      service_name: todo-backend
      service_port: 8000
      docker_image: "${{env.image}}"
      tier: "backend"
    secrets: inherit